### ISSUE TITLE
Issue with `post_attention` Function

### ISSUE THREAD

**Issue by zero1778** [genmoai/mochi#106]
I encountered the following error while running the default command: 
`python3 ./demos/cli.py --model_dir weights/`

Error message:
<code> File "/path/models/src/genmo/mochi_preview/dit/joint_model/asymm_models_joint.py", line 294, in post_attention
    assert x.size() == (B, M, local_dim)
</code>

This issue seems to have arisen after the recent update to the `post_attention` function, even though I used the default configuration. Could you please investigate? Moreover, I run in the Multi-GPU mode

**Comment by paras-genmo** [comment]
Thank you for reporting. This is now fixed with https://github.com/genmoai/mochi/commit/fbf8a68d3c27c3a8e750171cd482af55001857dc. Our single-GPU LoRA changes introduced the assertion error on multi-GPU.
