### ISSUE TITLE
"A fun, playful scene where a young man and a young woman are joking and laughing together in a lush garden. They are in a light-hearted mood, exchanging jokes with big smiles on their faces. The background is a vibrant green garden with blooming flowers and trees. The video is shot in a 16:9 ratio with a green screen effect so that the background can be replaced with any desired setting. The characters should be animated with exaggerated expressions, and the scene should have a lively, comedic tone. Both characters are dressed casually and look relaxed, making it perfect for a humorous, cheerful interaction."

### ISSUE THREAD

**Issue by Rambhau101** [genmoai/mochi#109]
"A fun, playful scene where a young man and a young woman are joking and laughing together in a lush garden. They are in a light-hearted mood, exchanging jokes with big smiles on their faces. The background is a vibrant green garden with blooming flowers and trees. The video is shot in a 16:9 ratio with a green screen effect so that the background can be replaced with any desired setting. The characters should be animated with exaggerated expressions, and the scene should have a lively, comedic tone. Both characters are dressed casually and look relaxed, making it perfect for a humorous, cheerful interaction."

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the default prompt to match the requested scene description and adjusted the default video dimensions to 16:9 aspect ratio.

You can review changes in this commit: https://github.com/mnmnk43434/genmoai-mochi-109/commit/a7c0fb9370f65ca9f607e4a264a0b8ad1bc85401.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
