### ISSUE TITLE
Web monthly credits is not resetting.

### ISSUE THREAD

**Issue by CreppyMC** [genmoai/mochi#117]
### So here's the full story.

First of all, I ran out of my monthly credits in the free plan. And It just keeps saying a date over today's date saying the credits will reset in that day but it just keeps getting over and over again. For example:

If it says **The credits will reset in 16 Dec** , then when 16 Dec comes, it will say **The credits will reset in 17 Dec** and so on.
I waited over a month to see if it will go away but it does not. I hope this gets fixed. I don't know if this is just an issue on my part but can someone please help me?

Thank you.
-Creppy

**Comment by akbar-genmo** [comment]
Hi, thanks for bringing up this issue, I've shared the details with our product team. We will follow up on our discord which is the right channel for this kind of stuff :)

**Comment by sidd-genmo** [comment]
Hey @CreppyMC, I work on product at Genmo. Thank you for flagging this issue–we've pushed out a fix that should be ready  soon. 

In the meantime, do you mind sending me your genmo username? I'd like to grant you extra generation credits for bringing this up. If you have discord, we can continue the conversation there 😄

**Comment by CreppyMC** [comment]
> Hey [@CreppyMC](https://github.com/CreppyMC), I work on product at Genmo. Thank you for flagging this issue–we've pushed out a fix that should be ready soon.
> 
> In the meantime, do you mind sending me your genmo username? I'd like to grant you extra generation credits for bringing this up. If you have discord, we can continue the conversation there 😄

Sorry for the delayed reply. Here's my Genmo username "TroubledBlueberry3". If I don't get the extra credits. That's ok. Thanks for solving this issue.

**Comment by CreppyMC** [comment]
> Hey [@CreppyMC](https://github.com/CreppyMC), I work on product at Genmo. Thank you for flagging this issue–we've pushed out a fix that should be ready soon.
> 
> In the meantime, do you mind sending me your genmo username? I'd like to grant you extra generation credits for bringing this up. If you have discord, we can continue the conversation there 😄

Sorry for the delayed reply. Here's my Genmo username "TroubledBlueberry3". If I don't get the extra credits. That's ok. Thanks for solving this issue.
