### ISSUE TITLE
diffusers bfloat16 inference error: OSError: Error no file named diffusion_pytorch_model.bf16.bin found in directory

### ISSUE THREAD

**Issue by AlphaNext** [genmoai/mochi#119]
First, I download all about bfloat16 weights from [https://huggingface.co/genmo/mochi-1-preview/tree/main/transformer](https://huggingface.co/genmo/mochi-1-preview/tree/main/transformer)

Next, use this script to load model and inference.
```
import torch
from diffusers import MochiPipeline
from diffusers.utils import export_to_video

pipe = MochiPipeline.from_pretrained("/home/mochi-1-preview", torch_dtype=torch.bfloat16)
pipe.enable_model_cpu_offload()
pipe.enable_vae_tiling()
prompt = "Close-up of a chameleon's eye, with its scaly skin changing color. Ultra high resolution 4k."
frames = pipe(prompt, num_inference_steps=28, guidance_scale=3.5).frames[0]
export_to_video(frames, "mochi.mp4")
```

Finally, get this error:

```
diffusers/src/diffusers/utils/hub_utils.py", line 309, in _get_model_file
OSError: Error no file named diffusion_pytorch_model.bf16.bin found in directory
```

**Comment by sayakpaul** [comment]
How did you download the `/home/genmo-1-preview` content? 

Also, this issue might be better off here: https://github.com/huggingface/diffusers/issues/new.

**Comment by AlphaNext** [comment]
> How did you download the `/home/genmo-1-preview` content?
> 
> Also, this issue might be better off here: https://github.com/huggingface/diffusers/issues/new.

Download all weight files from [https://huggingface.co/genmo/mochi-1-preview/tree/main](https://huggingface.co/genmo/mochi-1-preview/tree/main), for vae and transformer only download the bf16 type models.

**Comment by sayakpaul** [comment]
Just downloading the `.safetensors` files won't be enough. 

You need to download the [`config.json`](https://huggingface.co/genmo/mochi-1-preview/blob/main/transformer/config.json) as well as the [index file](https://huggingface.co/genmo/mochi-1-preview/blob/main/transformer/diffusion_pytorch_model.safetensors.index.json) that provides a mapping for the sharded state dict.

**Comment by AlphaNext** [comment]
@sayakpaul Yes, I have downloaded these files, for examples:
transformer folders:
  -- config.json
  -- transformer_config.json
  -- transformer_diffusion_pytorch_model.safetensors.index.bf16.json
  -- diffusion_pytorch_model.bf16-00003-of-00003.safetensors
  -- diffusion_pytorch_model.bf16-00002-of-00003.safetensors
  -- diffusion_pytorch_model.bf16-00001-of-00003.safetensors

vae folders:
  -- config.json
  -- diffusion_pytorch_model.bf16.safetensors

text_encoder folders:
  -- config.json
  -- model.safetensors.index.json
  -- model-00001-of-00002.safetensors
  -- model-00002-of-00002.safetensors

**Comment by sayakpaul** [comment]
Can you clear your downloaded folder and do:

```py
repo_id = "genmo/mochi-1-preview"
pipe = MochiPipeline.from_pretrained(repo_id, variant="bf16")
```

**Comment by AlphaNext** [comment]
@sayakpaul This is a part log when running the above code, there is also no *.bin (diffusion_pytorch_model.bf16.bin) model files.
```
A mixture of bf16 and non-bf16 filenames will be loaded.
Loaded bf16 filenames:
[transformer/diffusion_pytorch_model.bf16-00003-of-00003.safetensors, vae/diffusion_pytorch_model.bf16.safetensors, transformer/diffusion_pytorch_model.bf16-00002-of-00003.safetensors, transformer/diffusion_pytorch_model.bf16-00001-of-00003.safetensors]
Loaded non-bf16 filenames:
[text_encoder/model-00001-of-00004.safetensors, text_encoder/model-00001-of-00002.safetensors, text_encoder/model-00002-of-00002.safetensors, text_encoder/model-00004-of-00004.safetensors, text_encoder/model-00003-of-00004.safetensors, text_encoder/model-00002-of-00004.safetensors
If this behavior is not expected, please check your folder structure.
```

**Comment by AlphaNext** [comment]
> @sayakpaul Yes, I have downloaded these files, for examples:
> 
> transformer folders: -- config.json -- transformer_diffusion_pytorch_model.safetensors.index.bf16.json -- diffusion_pytorch_model.bf16-00003-of-00003.safetensors -- diffusion_pytorch_model.bf16-00002-of-00003.safetensors -- diffusion_pytorch_model.bf16-00001-of-00003.safetensors
> 
> vae folders: -- config.json -- diffusion_pytorch_model.bf16.safetensors
> 
> text_encoder folders: -- config.json -- model.safetensors.index.json -- model-00001-of-00002.safetensors -- model-00002-of-00002.safetensors

@sayakpaul Thank you for your reply. This problem is solved. Because when I downloaded the weights manually, the file name was automatically prefixed with "transformer_", the ```transformer_diffusion_pytorch_model.safetensors.index.bf16.json``` file name should be ```diffusion_pytorch_model.safetensors.index.bf16.json```
