### ISSUE TITLE
The use of Transformer Engine and fp8 training

### ISSUE THREAD

**Issue by TheTinyTeddy** [genmoai/mochi#12]
Hi

Thank you very much for the great work!

I saw the config contains a row stating "use_transformer_engine: true", so I was wondering if you use fp8 Linear, fp8 flash attention 3 or  mixed fp8/fp16 precision for training? 

Furthermore, could you let us know your experience of stability of fp8 training? I thought this would be very helpful for the community to understand the whole process.

Many thanks!

**Comment by paras-genmo** [comment]
Hi @TheTinyTeddy, transformer engine isn't supported in this repo. Some community members have had success with fp8 inference of Mochi, such as the official [ComfyUI workflow](https://comfyanonymous.github.io/ComfyUI_examples/mochi/).

For the best quality, we recommend autocasting to bfloat16 in the forward pass.
