### ISSUE TITLE
Compatibility with Standard DPM++ Sampler

### ISSUE THREAD

**Issue by alfredplpl** [genmoai/mochi#25]
## Summary
The current diffusion model in this repository uses a custom sampler implementation. I would like to verify if standard DPM++ samplers can be used as an alternative.

## Current Situation
- There are significant differences from standard DPM++ samplers that need compatibility verification

## Questions
1. Is the standard DPM++ sampler (DPM-Solver) compatible with this implementation?
2. If not compatible, what are the technical constraints or reasons?
3. Are there any plans to add support for standard DPM++ samplers in future updates?

Thank you for your help.

**Comment by ved-genmo** [comment]
@yan-genmo

**Comment by paras-genmo** [comment]
@alfredplpl My understanding is the DPM-Solver is defined for the variance-preserving DDPM (diffusion model) setting, while Mochi is a rectified flow model. Our codebase implements an Euler sampler. [Sana](https://arxiv.org/pdf/2410.10629) proposes a Flow-DPM-Solver that may be useful.

If you test Flow-DPM-Solver on Mochi, I would enjoy seeing the results and we would be happy to review a pull-request to upstream the solver to this repository.
