### ISSUE TITLE
No module named 'genmo'

### ISSUE THREAD

**Issue by MinervaArgus** [genmoai/mochi#35]
(.venv) D:\PyShit\genmo-test\models>python3 ./demos/gradio_ui.py --model_dir "D:\PyShit\genmo-test\genmoModels"

Traceback (most recent call last):
  File "D:\PyShit\genmo-test\models\demos\gradio_ui.py", line 9, in <module>
    from cli import generate_video, configure_model
  File "D:\PyShit\genmo-test\models\demos\cli.py", line 10, in <module>
    from genmo.mochi_preview.pipelines import (
ModuleNotFoundError: No module named 'genmo'

**Comment by ptits** [comment]
copy all py files from demos to root (models) folder
there is a mess with folders and paths (src\..)

**Comment by MinervaArgus** [comment]
> copy all py files from demos to root (models) folder there is a mess with folders and paths (src..)

still gives me the same error, i also tried 'python3 gradio_ui.py --model_dir "D:\PyShit\genmo-test\genmoModels"' and that did not work either

**Comment by arcinin1** [comment]
currently having problem with "genmo.lib".

Traceback (most recent call last):
  File "C:\Users\Wspolny\Desktop\models\demos\gradio_ui.py", line 10, in <module>
    from cli import configure_model, generate_video
  File "C:\Users\Wspolny\Desktop\models\demos\cli.py", line 10, in <module>
    from genmo.lib.progress import progress_bar
ModuleNotFoundError: No module named 'genmo.lib'

**Comment by piradata** [comment]
same problem here, someone got it solved?

**Comment by piradata** [comment]
ok, fixed it

**Comment by arcinin1** [comment]
> ok, fixed it

How did you fix it?

**Comment by khydrogenous** [comment]
Any updates on solving genmo.lib?

**Comment by piradata** [comment]
> > ok, fixed it
> 
> How did you fix it?

i did open a pr with the fix, but basically, it happens because either the path is not added correctly (adding .. to path is dependent on the directory you are curently in) and because evem if the path is added the lib should be referenced as src.genmo

**Comment by khydrogenous** [comment]
Thanks, I just solved it too after I realized that "your-dir" from python3 ./demos/cli.py --model_dir your-dir has to be the full path, it cannot include any wildcards or placeholders. Perhaps a Readme clarification would help?

**Comment by lavaraja** [comment]
after cloning the repo run `pip install -ve .` to fix `No module named 'genmo'` issue.
