### ISSUE TITLE
how to finetune t2v model

### ISSUE THREAD

**Issue by syyxsxx** [genmoai/mochi#56]
hello, i want to finetune the t2v model with lora, how can i do this

**Comment by oliverban** [comment]
Yes, in the blog post they state that "the community will probably finetune further styles" but there is no mention of finetuning the mochi 1 preview model anywhere. Is this the case?

**Comment by paras-genmo** [comment]
@syyxsxx LoRA fine-tuning support is now live. Check out https://github.com/genmoai/mochi/tree/main/demos/fine_tuner to test it out.
