### ISSUE TITLE
How to get a video with the same time length as Genmo website.

### ISSUE THREAD

**Issue by lep990816** [genmoai/mochi#92]
I wonder if the code only supports 30 frames for inference results. We found that the result generated by increasing num_frames (like 150) likes the result of stitching five 1s videos. How to get a video with the same time length as Genmo website.
Here is a 150 frames results:
https://github.com/user-attachments/assets/2a84db0c-ec95-4b6c-bb81-49176c768285

**Comment by lep990816** [comment]
prompt: A cat grooming itself meticulously with its tongue.
https://github.com/user-attachments/assets/5a7ad228-d6b6-4624-b2c3-157c6b98f9a9

**Comment by akbar-genmo** [comment]
You can specify num_frames here: https://github.com/genmoai/mochi/blob/fbf8a68d3c27c3a8e750171cd482af55001857dc/demos/api_example.py#L42

Please look at Issue #37 on how to set number of frames properly.
