### ISSUE TITLE
TypeError: configure_model() missing 1 required positional argument: 'cpu_offload_'

### ISSUE THREAD

**Issue by ysxk** [genmoai/mochi#93]
TypeError: configure_model() missing 1 required positional argument: 'cpu_offload_'
start gradio
I will encounter this problem regardless of whether I pass this parameter or not
Here are some startup parameters I have tried
python3 ./demos/gradio_ui.py --model_dir weights/ --cpu_offload true
python3 ./demos/gradio_ui.py --model_dir weights/ --cpu_offload false
python3 ./demos/gradio_ui.py --model_dir weights/

**Comment by paras-genmo** [comment]
Hi @ysxk, this is a bug introduced by our LoRA trainer. I'm working on a fix which should be out soon. In the meantime, `./demos/cli.py` works. Thanks for reporting!

**Comment by paras-genmo** [comment]
@ysxk gradio_ui.py is now fixed. You can use it with:
```
python3 ./demos/gradio_ui.py --model_dir weights/ --cpu_offload
```
or
```
python3 ./demos/gradio_ui.py --model_dir weights/
```

**Comment by ysxk** [comment]
thanks
