### ISSUE TITLE
Model does not work without Lora

### ISSUE THREAD

**Issue by robinchm** [genmoai/mochi#95]
After introducing the Lora thing, the model no longer works without Lora.

I think the cause is here:

https://github.com/genmoai/mochi/blob/f3a800aea5862b4af13e66ff77eea1967c8c3a7f/src/genmo/mochi_preview/dit/joint_model/asymm_models_joint.py#L95

The initialization of `AsymmetricAttention` does not correctly handle the case where no Lora is used (the default) but raises. I think using the default arguments the `LoraLinear` block is equivalent to the old `Linear` block, so fixing the condition check in the `if` block should solve the issue?

**Comment by paras-genmo** [comment]
Thank you for flagging, @robinchm! I just merged a fix for this case. Could you try again?

**Comment by paras-genmo** [comment]
It seems there is still an issue. Working on fixing it.
