### ISSUE TITLE
Error "CP group not initialized"

### ISSUE THREAD

**Issue by Curlypla** [genmoai/mochi#98]
I use modal script and defaultl dataset, during preprocessing Step 1 works fine but during Step 2 I get errors in all the videos processed:

```
🎥 **Step 2: Run the VAE encoder on each video**
Timing load_encoder
Timing load_decoder
Stage                   Time(s)    Percent
load_encoder               1.12     28.88%
load_decoder               2.76     71.12%
Traceback (most recent call last)::00<00:05, 2.42it/s]
  File "/mochi/demos/fine_tuner/encode_videos.py", line 132, in batch_process
    preprocess(
  File "/mochi/demos/fine_tuner/encode_videos.py", line 65, in preprocess
    ldist.mean = cp_conv.gather_all_frames(ldist.mean)
  File "/mochi/src/genmo/mochi_preview/vae/cp_conv.py", line 67, in gather_all_frames
    cp_group = cp.get_cp_group()
  File "/mochi/src/genmo/mochi_preview/dit/joint_model/context_parallel.py", line 48, in get_cp_group
    raise RuntimeError("CP group not initialized")
RuntimeError: CP group not initialized00:29, 2.11s/it]
```

**Comment by erik-dunteman** [comment]
working on this now

**Comment by erik-dunteman** [comment]
I'm not able to replicate this, neither on my cached version of the [git clone](https://github.com/genmoai/mochi/blob/f3a800aea5862b4af13e66ff77eea1967c8c3a7f/contrib/modal/main.py#L22) from when the example was written, nor on the current main commit if I clear my build cache.

So will need help from you on repro:

1. please confirm your script is unmodified from the example. If modified, please share the whole script here.

2. please confirm that you've run `modal run main::download_videos` and `modal run main::download_weights`

3. make the below modification and share the commit hash here.
```
base_img = (
    modal.Image.debian_slim()
    .apt_install("git", "ffmpeg", "bc", "zlib1g-dev", "libjpeg-dev", "wget")
    .run_commands(CLONE_CMD)
    .workdir(REPOSITORY)
    .run_commands("git rev-parse HEAD") #  <-------- This
    .pip_install("gdown", "setuptools", "wheel")
    .run_commands('pip install -e . --no-build-isolation')
)
```
and the build should show you the commit you've checked out. Something like:
```
=> Step 1: RUN git rev-parse HEAD
f3a800aea5862b4af13e66ff77eea1967c8c3a7f
```

Thanks

**Comment by erik-dunteman** [comment]
I tested on the prior commit `abe3e102f40408bbf46cfda3928fc44f28a663c4` and it works without issue. Meaning the source of the regression is somewhere in https://github.com/genmoai/mochi/commit/f3a800aea5862b4af13e66ff77eea1967c8c3a7f 

cc @ajayjain

**Comment by paras-genmo** [comment]
@Curlypla @erik-dunteman We're working on fixing the regression with https://github.com/genmoai/mochi/pull/99/files

https://github.com/genmoai/mochi/commit/f3a800aea5862b4af13e66ff77eea1967c8c3a7f simplifies video encoding by only needing a single GPU, but it looks like there was a collective communication that was not removed.

**Comment by paras-genmo** [comment]
@erik-dunteman could you try again? Thanks!

**Comment by Curlypla** [comment]
It works now on latest commit, thanks!

However, the modal script would have to be modified by adding a larger timeout for preprocessing, otherwise it won't have time to finish (I put it at 30 minutes and works fine)

**Comment by erik-dunteman** [comment]
Timeout bumped to 30min as requested
https://github.com/genmoai/mochi/pull/105
